### ISSUE TITLE
Deploy failing

### ISSUE THREAD

**Issue by avdi** [avdi/ppwm#81]
I've been getting failed deploy emails from Heroku. The emails suggest re-connecting to GitHub, so I did. Keeping this open until we confirm that it worked...

> An automatic deployment for ppwm failed. The build failed with the message Unauthorized.
> 
> Token from user contact@shiprise.net was used to interact with GitHub. This account was matched as the GitHub committer.
> 
> You can also check that the user who connected the app or pipeline to GitHub still has access to the app and to the Github repository.
> 
> In this case, reconnecting to GitHub will often fix the issue.
> 
> If you believe that this build failure was not due to an issue in your app, please open a support ticket.

**Comment by hanneskaeufler** [comment]
I just merged #82 a few minutes ago but it doesn't seem to go live. Should've been picked up by heroku by now ... Did you get another failure email by any chance?

Thanks

**Comment by avdi** [comment]
uuuugh it's still failing with the exact same highly informative message 


OK, what is the best way to deal with this that removes me as the debug bottleneck?

—
Avdi Grimm

--- original message ---
On January 14, 2020, 3:09 PM EST notifications@github.com wrote:


I just merged #82 a few minutes ago but it doesn't seem to go live. Should've been picked up by heroku by now ... Did you get another failure email by any chance?

Thanks

—

You are receiving this because you were assigned.

Reply to this email directly, view it on GitHub, or unsubscribe.
--- end of original message ---

**Comment by hanneskaeufler** [comment]
I think you might be able to add me as a collaborator to heroku: https://devcenter.heroku.com/articles/collaborating. My heroku mail is hannes.kaeufler at gmail.com. From there on I can have a look and see whats failing exactly. Would that work for you?

**Comment by avdi** [comment]
Added! Let me know if that works.

—
Avdi Grimm

--- original message ---
On January 18, 2020, 5:41 AM EST notifications@github.com wrote:


I think you might be able to add me as a collaborator to heroku: https://devcenter.heroku.com/articles/collaborating. My heroku mail is hannes.kaeufler at gmail.com. From there on I can have a look and see whats failing exactly. Would that work for you?

—

You are receiving this because you were assigned.

Reply to this email directly, view it on GitHub, or unsubscribe.
--- end of original message ---

**Comment by hanneskaeufler** [comment]
> Added! Let me know if that works. — Avdi Grimm
> […](#)

It did! I was able to enable automatic deploys and deploy from master. Updates from my PRs are live 👍 Will do one more merge now and then close this.
